---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openshift-backup
  namespace: ocp-etcd-backup
  labels:
    app: etcd
    component: backup

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: use-privileged-scc
  namespace: ocp-etcd-backup
rules:
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    verbs:
      - use
    resourceNames:
      - privileged

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openshift-backup-sa-privileged
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: use-privileged-scc
subjects:
  - kind: ServiceAccount
    name: openshift-backup
    namespace: ocp-etcd-backup