apiVersion: v1
kind: PersistentVolume
metadata:
  name: openshift-backup-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  nfs:
    server: truenas.openshift.training
    path: "/mnt/main-pool/NFS"
  capacity:
    storage: 10Gi
  claimRef:
    name: openshift-backup-pvc
    namespace: ocp-etcd-backup
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openshift-backup-pvc
  namespace: ocp-etcd-backup
spec:
  volumeName: openshift-backup-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
